### ISSUE TITLE
Budget Proposal

### ISSUE THREAD

**Issue by vnmercouris** [Java-Like-Its-Hot-Robotics/Power-Play#3]
Create a full budget proposal for Newman so that way we can get this seasons funds. It should include but is not limited to, T-shirts, competition, and field fees. This should be completed and turned in by Friday September 16th.

**Comment by jbans5780** [comment]
The first draft is written. Located in shared drive --> current files --> budget proposal. Need to format, print, and submit

**Comment by vnmercouris** [comment]
Second draft completed. Just waiting on the tee-shirt budget and approval and signature from captains.

**Comment by vnmercouris** [comment]
Submitted to Mr. Cooper 9/16

**Comment by Tommyg26** [comment]
Ok, let me know when he responds.
