### ISSUE TITLE
Pick Out Webcam

### ISSUE THREAD

**Issue by vnmercouris** [Java-Like-Its-Hot-Robotics/Power-Play#6]
Whoever wants to deal with computer vision for the robot need to pick out a camera that will be in our budget. Once you pick it out move this to my shopping list with a link for the camera.

**Comment by MayaHarris25** [comment]
https://www.amazon.com/dp/B085TFF7M1/ref=sspa_dk_detail_0?pd_rd_i=B085TFF7M1&pd_rd_w=N5Xyt&content-id=amzn1.sym.dd2c6db7-6626-466d-bf04-9570e69a7df0&pf_rd_p=dd2c6db7-6626-466d-bf04-9570e69a7df0&pf_rd_r=82N55HYY78DVRP4EGH4X&pd_rd_wg=eJ03i&pd_rd_r=aa70f5c7-03ad-4e2d-937e-075bfe00c631&s=pc&sp_csd=d2lkZ2V0TmFtZT1zcF9kZXRhaWxfdGhlbWF0aWM&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUExRk9QWDVLTUc0RklGJmVuY3J5cHRlZElkPUEwMjk4MzQ1MkhEWjNWVTlPMEo5WCZlbmNyeXB0ZWRBZElkPUEwMTI1NTAyMkRSVjhTV0ExUEYwOCZ3aWRnZXROYW1lPXNwX2RldGFpbF90aGVtYXRpYyZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU&th=1

**Comment by vnmercouris** [comment]
Got camera from SWAP shop.
